server.port=8080
server.servlet.context-path=/
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PWD:change_me}
spring.datasource.url=${DB_URL:jdbc:mysql:///pethome?useUnicode=true&characterEncoding=utf8&useSSL=false}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
logging.level.org.yjhking.pethome=trace
mybatis.type-aliases-package=org.yjhking.pethome.*.domain,org.yjhking.pethome.*.query
spring.mail.host=${MAIL_HOST:smtp.qq.com}
#spring.mail.port=465
spring.mail.username=${MAIL_USER:example@qq.com}
spring.mail.password=${MAIL_PWD:change_me}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.redis.database=${REDIS_DATABASE:0}
spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=${REDIS_PORT:6379}
spring.redis.password=${REDIS_PWD:}
spring.redis.jedis.pool.max-active=8
spring.redis.jedis.pool.min-idle=2
spring.redis.jedis.pool.max-idle=8
spring.redis.jedis.pool.max-wait=2000ms
spring.freemarker.allow-request-override=false
spring.freemarker.cache=true
spring.freemarker.check-template-location=true
spring.freemarker.charset=UTF-8
spring.freemarker.suffix=.ftl
spring.freemarker.templateEncoding=UTF-8
spring.freemarker.templateLoaderPath=classpath:/templates
spring.freemarker.expose-request-attributes=true
spring.freemarker.expose-session-attributes=true
spring.freemarker.expose-spring-macro-helpers=true
templatedir=${TEMPLATE_DIR:classpath:/templates}
htmldir=${HTML_DIR:./pethome_front/pethome_user/pet}
